# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_management', '0002_auto_20171209_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('unit', models.CharField(max_length=10, verbose_name='單位')),
                ('count', models.IntegerField(verbose_name='數量')),
                ('price', models.FloatField(verbose_name='單價')),
                ('amount', models.FloatField(verbose_name='金額')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('total_amount', models.FloatField(verbose_name='總金額')),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_management.Categorie', verbose_name='分類')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('Manufacturer_Info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_management.Manufacturer_Information', verbose_name='廠商')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_management.Employee_Info', verbose_name='處理人員')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Goods_management.Detail', verbose_name='單身')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Goods_management.Master', verbose_name='單頭')),
            ],
        ),
    ]
