# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_management', '0002_auto_20171209_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='售價')),
                ('num_of_product', models.IntegerField(verbose_name='數量')),
                ('subtotal', models.IntegerField(verbose_name='小計')),
                ('remark', models.TextField(verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10, verbose_name='統一編號')),
                ('date', models.DateTimeField(verbose_name='輸入日期')),
                ('estimated_shipping_date', models.DateTimeField(verbose_name='預計出貨日期')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='送貨地址')),
                ('total', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='合計')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Client_Info', verbose_name='客戶id')),
            ],
        ),
        migrations.CreateModel(
            name='Returns_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('returns_reason', models.TextField(max_length=500, verbose_name='退貨原因')),
                ('returns_type', models.CharField(choices=[('E', 'Exchange'), ('R', 'Return')], default='E', max_length=2, verbose_name='退/換貨')),
                ('total', models.IntegerField(verbose_name='合計')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Client_Info', verbose_name='會員編號')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('total', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='合計')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Client_Info', verbose_name='客戶')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('details_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_management.Details_base')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.Order_Info', verbose_name='訂貨單號')),
            ],
            bases=('sales_management.details_base',),
        ),
        migrations.CreateModel(
            name='Returns_Detail',
            fields=[
                ('details_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_management.Details_base')),
                ('returns_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.Returns_Info', verbose_name='退貨單號')),
            ],
            bases=('sales_management.details_base',),
        ),
        migrations.CreateModel(
            name='Sales_Detail',
            fields=[
                ('details_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales_management.Details_base')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.Sales_Info', verbose_name='出貨單號')),
            ],
            bases=('sales_management.details_base',),
        ),
        migrations.AddField(
            model_name='details_base',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Product_Information', verbose_name='商品id'),
        ),
    ]
