# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=200, null=True)),
                ('client_phonenumber', models.CharField(max_length=200)),
                ('client_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('client_birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('comp_address', models.CharField(max_length=200)),
                ('comp_phonenumber', models.CharField(max_length=200)),
                ('comp_EIN', models.CharField(max_length=50)),
                ('comp_person_in_charge', models.CharField(max_length=20)),
                ('comp_NUM_employee', models.IntegerField()),
                ('comp_email', models.EmailField(max_length=254)),
                ('comp_introduction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=200, null=True)),
                ('emp_phonenumber', models.CharField(max_length=200)),
                ('emp_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('emp_birthday', models.DateField()),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_management.Company_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uniform_numbers', models.CharField(max_length=100)),
                ('ManuFacturer_name', models.CharField(max_length=100)),
                ('Total_capital', models.IntegerField()),
                ('Name_of_representative', models.CharField(max_length=100)),
                ('Company_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Hight', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Categories')),
            ],
        ),
    ]
