# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phonenumber', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('EIN', models.CharField(max_length=50)),
                ('person_in_charge', models.CharField(max_length=20)),
                ('NUM_employee', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phonenumber', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Hight', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer_Information',
            fields=[
                ('company_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic_management.Company_Info')),
                ('Uniform_numbers', models.CharField(max_length=100)),
                ('Total_capital', models.IntegerField()),
            ],
            bases=('basic_management.company_info',),
        ),
        migrations.AddField(
            model_name='employee_info',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_management.Company_Info'),
        ),
    ]
