# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie_name', models.CharField(max_length=100, verbose_name='分類')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phonenumber', models.CharField(max_length=200, verbose_name='電話')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='性別')),
                ('birthday', models.DateField(verbose_name='生日')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('phonenumber', models.CharField(max_length=200, verbose_name='公司電話')),
                ('EIN', models.CharField(max_length=50, verbose_name='統一編號')),
                ('person_in_charge', models.CharField(max_length=20, verbose_name='負責人')),
                ('NUM_employee', models.IntegerField(verbose_name='公司人數')),
                ('email', models.EmailField(max_length=254)),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='公司簡介')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='員工姓名')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phonenumber', models.CharField(max_length=200, verbose_name='電話')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='性別')),
                ('birthday', models.DateField(verbose_name='生日')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('Hight', models.FloatField(verbose_name='高度')),
                ('Weight', models.FloatField(verbose_name='重量')),
                ('Categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer_Information',
            fields=[
                ('company_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic_management.Company_Info')),
                ('Total_capital', models.IntegerField(verbose_name='資本額')),
            ],
            bases=('basic_management.company_info',),
        ),
        migrations.AddField(
            model_name='employee_info',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_management.Company_Info'),
        ),
        migrations.AddField(
            model_name='employee_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='m_models.AuthUser'),
        ),
    ]
