# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uniform_numbers', models.CharField(max_length=100)),
                ('ManuFacturer_name', models.CharField(max_length=100)),
                ('Total_capital', models.IntegerField()),
                ('Name_of_representative', models.CharField(max_length=100)),
                ('Company_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Hight', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Categories')),
            ],
        ),
    ]
