# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_info',
            old_name='client_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='client_birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='client_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='client_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client_info',
            old_name='client_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='comp_EIN',
            new_name='EIN',
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='comp_NUM_employee',
            new_name='NUM_employee',
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='comp_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='comp_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='comp_introduction',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='comp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='comp_person_in_charge',
            new_name='person_in_charge',
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='comp_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emp_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emp_birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emp_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emp_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emp_phonenumber',
            new_name='phonenumber',
        ),
    ]
