# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='m_models.AuthUser', verbose_name='帳號'),
        ),
    ]
