# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Categorie_name',
            field=models.CharField(max_length=100, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='address',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='name',
            field=models.CharField(max_length=100, verbose_name='客戶名稱'),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='phonenumber',
            field=models.CharField(max_length=200, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='EIN',
            field=models.CharField(max_length=50, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='NUM_employee',
            field=models.IntegerField(verbose_name='公司人數'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='address',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='公司簡介'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='name',
            field=models.CharField(max_length=100, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='person_in_charge',
            field=models.CharField(max_length=20, verbose_name='負責人'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='phonenumber',
            field=models.CharField(max_length=200, verbose_name='公司電話'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='address',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='name',
            field=models.CharField(max_length=100, verbose_name='員工姓名'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='phonenumber',
            field=models.CharField(max_length=200, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='manufacturer_information',
            name='Total_capital',
            field=models.IntegerField(verbose_name='資本額'),
        ),
        migrations.AlterField(
            model_name='manufacturer_information',
            name='Uniform_numbers',
            field=models.CharField(max_length=100, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='product_information',
            name='Hight',
            field=models.FloatField(verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='product_information',
            name='Product_name',
            field=models.CharField(max_length=100, verbose_name='產品名稱'),
        ),
        migrations.AlterField(
            model_name='product_information',
            name='Weight',
            field=models.FloatField(verbose_name='重量'),
        ),
    ]
