# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_management', '0002_remove_manufacturer_information_uniform_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer_information',
            name='Total_capital',
        ),
    ]
