# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_management', '0002_categories_manufacturer_information_product_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='client_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee_info',
            name='emp_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='client_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='comp_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='comp_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emp_address',
            field=models.CharField(max_length=200),
        ),
    ]
