# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_management', '0002_auto_20171126_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer_information',
            name='Uniform_numbers',
        ),
    ]
