# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_management', '0003_auto_20171123_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_info',
            name='client_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='emp_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=2),
        ),
    ]
