# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_management', '0002_auto_20171209_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_management.Product_Information', verbose_name='商品')),
            ],
        ),
    ]
